name: deploy-dev

on:
  workflow_dispatch:

env: 
  PROJECT_ID: ${{ secrets.GCP_PROJECT_DEV }} 
  REGION: europe-west1
  REPO_NAME: qeeps-application-service
  
jobs:
  build-and-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # Authenficate with Google Cloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY_DEV }}"

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker
      
      - name: Build and tag the docker image
        # For mac ARM chip
        # docker buildx build --platform linux/amd64 -t gcr.io/$PROJECT_ID/$REPO_NAME .
        run: |- 
          docker buildx build --platform linux/amd64 -t gcr.io/$PROJECT_ID/$REPO_NAME .
      
      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push gcr.io/$PROJECT_ID/$REPO_NAME
      
      - name: Deploy to Cloud Run 
        run: |-
          gcloud run deploy $REPO_NAME \
          --region $REGION \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:latest \
          --set-env-vars="MONGO_URI=${{ secrets.MONGO_URI_DEV }}" \
          --set-env-vars="TOKEN_KEY=${{ secrets.TOKEN_KEY_DEV }}" \
          --set-env-vars="MAIN_TOKEN_KEY=${{ secrets.MAIN_TOKEN_KEY_DEV}}" \
          --allow-unauthenticated \
          --port 8080
